export const styles = {
  leftSplit: {
    height: "100%",
    width: "20%",
    position: "absolute",
    left: "0",
    top: "0",
    paddingTop: "5px",
    backgroundColor: "#fff",
    borderLeft: "none",
    borderRight: "1px solid #dcdcde",
    display: "flex",
    flexDirection: "column",
    flexShrink: "0",
    transition: "transform 200ms ease-in-out",
  },
  rightSplit: {
    width: "80%",
    fontSize: "18px",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    flexShrink: "0",
    position: "absolute",
    right: "0",
  },
  leftOff: {
    display: "none",
  },
  rightFull: {
    width: "100%",
    fontSize: "18px",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    flexShrink: "0",
    position: "absolute",
    right: "0",
  },
};
